name: release

on:
  push:
    branches:
      - alpha
      - beta
      - master
    tags:
      - '!*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1.0.0

      - uses: actions/setup-node@v1.2.0
        with:
          node-version: 12

      - name: Install
        run: npm ci

      - name: Release
        run: npm run release
        env:
          NPM_TOKEN: ${{secrets.NPM_TOKEN}}
          GH_TOKEN: ${{secrets.GH_TOKEN}}
