name: 🔀 Merge

on:
  workflow_dispatch:
    inputs:
      from:
        required: true
      to:
        required: true
  workflow_call:
    inputs:
      from:
        required: true
        type: string
      to:
        required: true
        type: string

jobs:
  merge:
    name: 🔀 Merge
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: 🚚 Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 🔀 Merge '${{ inputs.from }}' into '${{ inputs.to }}'
        continue-on-error: true
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"

          git switch ${{ inputs.to }}
          git merge ${{ inputs.from }}
          git push origin ${{ inputs.to }}